### PR TITLE
Bootstrap upgrade to v3

### PR DESCRIPTION
**Pull request by cianclarke**

### CODE REVIEW

**Comment by cianclarke** [comment]
(Only https://github.com/cianclarke/fh-api-mapper/commit/354813eaf751d7dee6ce8586dabd2aa10e9452a3 needs review, the other is just removing a bunch of bootstrap and adding a bunch of bootstrap!)

**Comment by cianclarke** [comment]
@lfryc Any chance you could review this?

**Comment by lfryc** [comment]
@cianclarke sure, looks good to me.

I believe that there some small design glitches, but we can address them later once we have a big picture.

**Comment by lfryc** [comment]
```
Running "jshint:all" (jshint) task

   lib/models/request.js
     76 |    return request.save(function(err, saveResult){
                                               ^ 'saveResult' is defined but never used.

>> 1 error in 30 files
```

**Comment by cianclarke** [comment]
(Fixed in https://github.com/cianclarke/fh-api-mapper/pull/5)

**Pull request merged**
