### PR TITLE
Added treeview with working mapping update

### PR DESCRIPTION
**Pull request by cianclarke**

### CODE REVIEW

**Comment by lfryc** [comment]
@cianclarke when I open this in Chrome, I get:

```
bootstrap-treeview.min.js:1 Uncaught TypeError: Cannot read property 'state' of undefined
```

**Comment by lfryc** [comment]
```
Running "jshint:all" (jshint) task

   lib/models/request.js
     75 |    return request.save(function(err, saveResult){
                                               ^ 'saveResult' is defined but never used.
   public/js/mapping.view.js
    106 |  },
            ^ Extra comma. (it breaks older versions of IE)
     41 |    var el = $(e.target);
                 ^ 'el' is defined but never used.
```

**Comment by cianclarke** [comment]
@lfryc Thanks - fixed the hint,a nd the treeview issue you were seeing (forgot to disallow mapping on non-json types)

**Comment by lfryc** [comment]
@cianclarke it is better now, but I'm still hitting some issues:

Sample data:
GET https://api.github.com/repos/aerogear/aerogear-unifiedpush-server/pulls
User-Agent: xyz

screenshot

**Comment by lfryc** [comment]
another issue is that tests are failing:

```
Internal error: { [AssertionError: '' == true]
  name: 'AssertionError',
  actual: '',
  expected: true,
  operator: '==',
  message: '\'\' == true',
  generatedMessage: true }
Internal error: { [AssertionError: '' == true]
  name: 'AssertionError',
  actual: '',
  expected: true,
  operator: '==',
  message: '\'\' == true',
  generatedMessage: true }
'AssertionError: \'\' == true\n    at /home/lfryc/workspaces/api-mapping/fh-api-mapper/test/unit/test-lib-requester.js:24:12\n    at Request._callback (/home/lfryc/workspaces/api-mapping/fh-api-mapper/lib/requester.js:66:12)\n    at Request.self.callback (/home/lfryc/workspaces/api-mapping/fh-api-mapper/node_modules/request/request.js:198:22)\n    at emitTwo (events.js:87:13)\n    at Request.emit (events.js:172:7)\n    at Request.<anonymous> (/home/lfryc/workspaces/api-mapping/fh-api-mapper/node_modules/request/request.js:1073:14)\n    at emitOne (events.js:82:20)\n    at Request.emit (events.js:169:7)\n    at IncomingMessage.<anonymous> (/home/lfryc/workspaces/api-mapping/fh-api-mapper/node_modules/request/request.js:1019:12)\n    at emitNone (events.js:72:20)\n    at IncomingMessage.emit (events.js:166:7)\n    at endReadableNT (_stream_readable.js:893:12)\n    at doNTCallback2 (node.js:429:9)\n    at process._tickCallback (node.js:343:17)'
  1) it_should_send_get_requests
Warning: Command failed: /bin/sh -c mocha -A -u exports --recursive -t 10000 ./test/unit
Tue, 06 Oct 2015 17:14:33 GMT body-parser deprecated bodyParser: use individual json/urlencoded middlewares at node_modules/fh-mbaas-api/node_modules/fh-mbaas-express/lib/mbaas.js:152:13
Tue, 06 Oct 2015 17:14:33 GMT body-parser deprecated undefined extended: provide extended option at node_modules/fh-mbaas-api/node_modules/fh-mbaas-express/node_modules/body-parser/index.js:75:29
Internal error: { [AssertionError: '' == true]
  name: 'AssertionError',
  actual: '',
  expected: true,
  operator: '==',
  message: '\'\' == true',
  generatedMessage: true }
'AssertionError: \'\' == true\n    at /home/lfryc/workspaces/api-mapping/fh-api-mapper/test/unit/test-lib-requester.js:24:12\n    at Request._callback (/home/lfryc/workspaces/api-mapping/fh-api-mapper/lib/requester.js:66:12)\n    at Request.self.callback (/home/lfryc/workspaces/api-mapping/fh-api-mapper/node_modules/request/request.js:198:22)\n    at emitTwo (events.js:87:13)\n    at Request.emit (events.js:172:7)\n    at Request.<anonymous> (/home/lfryc/workspaces/api-mapping/fh-api-mapper/node_modules/request/request.js:1073:14)\n    at emitOne (events.js:82:20)\n    at Request.emit (events.js:169:7)\n    at IncomingMessage.<anonymous> (/home/lfryc/workspaces/api-mapping/fh-api-mapper/node_modules/request/request.js:1019:12)\n    at emitNone (events.js:72:20)\n    at IncomingMessage.emit (events.js:166:7)\n    at endReadableNT (_stream_readable.js:893:12)\n    at doNTCallback2 (node.js:429:9)\n    at process._tickCallback (node.js:343:17)'
```

**Comment by cianclarke** [comment]
@lfryc Can you re-test using Node 0.10? 
Known issue with 0.12 right now which I need to fix, but DF doesn't even support >0.10

As for the mapping not showing, can you try with `http://api.openweathermap.org/data/2.5/weather?q=London,uk`? 
The GitHub pull requests has an array at the root object. Right now, I've only completed support for Objects. 
Support for arrays and other types will be a (sizable!) future PR :-)

**Comment by cianclarke** [comment]
@lfryc Functionality fixed also in 0.12 now, tests should pass anywhere..

**Pull request merged**
